spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dmfldb
    username: dmflAdmin
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect